version: 2

models:
  - name: question_2-1_FundNAV
    description: >
      Fund-level Net Asset Value (NAV) over time. NAV is calculated as the latest valuation
      on or before a given date plus the sum of calls/distributions/commitments
      since that valuation up to the date.
    columns:
      - name: fund_name
        description: "Name of the fund."
        tests:
          - not_null

      - name: date
        description: "As-of date for the NAV."
        tests:
          - not_null

      - name: nav
        description: "Computed NAV of the fund on nav_date."
        tests:
          - not_null